SELECT TO_CHAR(SAMPLE_TIME, 'HH24:MI:SS') AS SAMPLE_TIME,
       TO_CHAR(SYSDATE, 'HH24:MI:SS') AS CURRENT_TIME,
       NVL(EVENT, 'ON CPU') AS EVENT
FROM V$ACTIVE_SESSION_HISTORY
WHERE SAMPLE_TIME > SYSDATE - 10/24/60
  AND MACHINE = 'INSPUR'
  AND MODULE = 'JDBC Thin Client'
ORDER BY SAMPLE_TIME;
