DEFINE dbid         = 2788912098
DEFINE inst_num     = 1
DEFINE service_name = SYS$USERS

WITH ServiceStats AS (
    SELECT
        SP.BEGIN_INTERVAL_TIME,
        SR.STAT_NAME,
        (SR.VALUE - LAG(SR.VALUE, 1, 0) OVER (
             PARTITION BY SR.INSTANCE_NUMBER, SR.STAT_NAME
             ORDER BY SP.BEGIN_INTERVAL_TIME
         )) AS VALUE_INCREMENT
    FROM
        DBA_HIST_SERVICE_STAT SR
    JOIN
        DBA_HIST_SNAPSHOT SP
          ON SP.DBID            = SR.DBID
         AND SP.SNAP_ID         = SR.SNAP_ID
         AND SP.INSTANCE_NUMBER = SR.INSTANCE_NUMBER
    WHERE
        SR.SERVICE_NAME = '&service_name'
        AND SP.BEGIN_INTERVAL_TIME >= SYSDATE - 1
        AND SP.DBID = &dbid
        AND SP.INSTANCE_NUMBER = &inst_num
)
SELECT
    TO_CHAR(BEGIN_INTERVAL_TIME, 'DD-MON HH24:MI') AS BEGIN_INTERVAL_TIME,
    MAX(CASE WHEN STAT_NAME = 'DB time' THEN VALUE_INCREMENT END) AS DB_TIME,
    MAX(CASE WHEN STAT_NAME = 'DB CPU' THEN VALUE_INCREMENT END) AS DB_CPU,
    MAX(CASE WHEN STAT_NAME = 'physical reads' THEN VALUE_INCREMENT END) AS READS,
    MAX(CASE WHEN STAT_NAME = 'physical writes' THEN VALUE_INCREMENT END) AS WRITES,
    MAX(CASE WHEN STAT_NAME = 'user I/O wait time' THEN VALUE_INCREMENT END) AS IO_WAIT_TIME,
    MAX(CASE WHEN STAT_NAME = 'logons cumulative' THEN VALUE_INCREMENT END) AS LOGONS,
    MAX(CASE WHEN STAT_NAME = 'redo size' THEN VALUE_INCREMENT END) AS REDO_SIZE,
    MAX(CASE WHEN STAT_NAME = 'parse count (total)' THEN VALUE_INCREMENT END) AS PARSE,
    MAX(CASE WHEN STAT_NAME = 'user calls' THEN VALUE_INCREMENT END) AS USER_CALLS,
    MAX(CASE WHEN STAT_NAME = 'execute count' THEN VALUE_INCREMENT END) AS EXECUTE
FROM
    ServiceStats
GROUP BY
    BEGIN_INTERVAL_TIME
ORDER BY
    BEGIN_INTERVAL_TIME;
