ALTER SYSTEM SET CONTROL_MANAGEMENT_PACK_ACCESS = NONE;

SELECT COUNT(*) FROM v$active_session_history;

ALTER SYSTEM SET CONTROL_MANAGEMENT_PACK_ACCESS = DIAGNOSTIC;

SELECT COUNT(*) FROM v$active_session_history;
